<?php

$quotes = array(
	array("who" => "zefrank", "quote" => "Celebrate Life"),
	array("who" => "zefrank", "quote" => "Respect The Time You Are Given"),
	array("who" => "zefrank", "quote" => "What Would The Hero You Do?"),
	array("who" => "rumoko", "quote" => "Follow Through"),
	array("who" => "Wally", "quote" => "humble confidence"),
	array("who" => "liz", "quote" => "you can think about why you don't want to do it while you're doing it."),
	array("who" => "liz", "quote" => "get over yourself"),
	array("who" => "Mike Garrett", "quote" => "Sleeper, awake! Rise from the dead, and Christ will shine on you."),
	array("who" => "Mary Ann", "quote" => "Right here, right now."),
	array("who" => "Elodie", "quote" => "This too shall pass"),
	array("who" => "Elodie", "quote" => "Be the change you want to see in the world"),
	array("who" => "Chrisopher", "quote" => "Justify your existence"),
	array("who" => "Ysa", "quote" => "Time - use it or lose it"),
	array("who" => "sarah", "quote" => "Relaxed concentration"),
	array("who" => "Sarah", "quote" => "Hope is the thing with feathers"),
	array("who" => "n0s0ap", "quote" => "Monkey: Sounds difficult. Teacher: Nothing is difficult, it is only thinking that makes it seem so."),
	array("who" => "n0s0ap", "quote" => "No matter where you go, there you are"),
	array("who" => "Ke Ruthe", "quote" => "Discipline is remembering what you want."),
	array("who" => "zero", "quote" => "do easy"),
	array("who" => "Derek", "quote" => "Own it"),
	array("who" => "Kelsey", "quote" => "Only today"),
	array("who" => "Kelsey", "quote" => "Breathe"),
	array("who" => "Kelsey", "quote" => "Look up [at the sky]"),
	array("who" => "Kelsey", "quote" => "Be spontaneous!"),
	array("who" => "Kelsey", "quote" => "I matter"),
	array("who" => "rocco", "quote" => "he not busy being born is busy dying"),
	array("who" => "Brian", "quote" => "People aren't afraid to die, they're afraid that they weren't living to begin with."),
	array("who" => "Doug", "quote" => "No one respects a bowler"),
	array("who" => " Doug", "quote" => "My heart has never been so open"),
	array("who" => " Doug", "quote" => "Waste anything but time"),
	array("who" => "Doug", "quote" => "Remember, you will die"),
	array("who" => "Doug", "quote" => "False wall"),
	array("who" => "alan", "quote" => "This too shall pass"),
	array("who" => "Ryan M", "quote" => "Why do I not care?"),
	array("who" => "Rubrick", "quote" => "What would Ze do?"),
	array("who" => "Steve", "quote" => "You never *have* to do *anything*"),
	array("who" => "Lian", "quote" => "Do Everything Better"),
	array("who" => "Sam", "quote" => "WORK WILL SET YOU FREE"),
	array("who" => "Kimmyesque", "quote" => "Believe you can do it. Then do it."),
	array("who" => "Kimmyesque", "quote" => "Grow a pair"),
	array("who" => "Kimmyesque", "quote" => "Stop apologizing and say something constructive for a change."),
	array("who" => "Kimmyesque", "quote" => "Shush...no more talking."),
	array("who" => "Marcus", "quote" => "No snowflake ever falls in the wrong place."),
	array("who" => "Drake", "quote" => "You will be compelled to manifest self-transformation."),
	array("who" => "Kate", "quote" => "notice"),
	array("who" => "Kate", "quote" => "Everything happens for a reason"),
	array("who" => "ingrid", "quote" => "Notice and Be Present"),
	array("who" => "Heather Meadows", "quote" => "live like the girl you want to be"),
	array("who" => "Rony", "quote" => "Food is Fuel"),
	array("who" => "xian", "quote" => "Thrive!"),
	array("who" => "AmazingAngie", "quote" => "We can not change the past, we can only make the future brighter!"),
	array("who" => "Justin D", "quote" => "Because people, are fucking crazy."),
	array("who" => "limbodog", "quote" => "Depression is your body's way of telling you that your life sucks and you need to change it."),
	array("who" => "Leigh", "quote" => "Only Human"),
	array("who" => "Paulie [eatl/ga]", "quote" => "Finish the job!"),
	array("who" => " Paulie [eatl/ga]", "quote" => "The legs are strong, the mind is weak"),
	array("who" => "Starchy", "quote" => "All is as it is, as am I"),
	array("who" => "teko", "quote" => "All things must pass"),
	array("who" => " teko", "quote" => "be here now"),
	array("who" => " teko", "quote" => "oh, what the hell"),
	array("who" => "Ginger", "quote" => "Life is too short too drink bad beer."),
	array("who" => "jpb", "quote" => "don't take the bait"),
	array("who" => "jpb", "quote" => "stay on target"),
	array("who" => "jpb", "quote" => "this machine will waste all yr time/if you let it"),
	array("who" => "Halcyon", "quote" => "Love More. Fear Less"),
	array("who" => "hoohash", "quote" => "RIIIIIIIIIIIIIICOLAAAAA!"),
	array("who" => "Toucan", "quote" => "Kill. People."),
	array("who" => "jenni", "quote" => "You will overcome difficult times"),
	array("who" => "jenni", "quote" => "You will be surrounded by things of luxury"),
	array("who" => "irene", "quote" => "saying it. doing it."),
	array("who" => "Jeremiah", "quote" => "Be greater than."),
	array("who" => "Atherton Bartelby", "quote" => "Let me be brave in the attempt"),
	array("who" => "Atherton Bartelby", "quote" => "Eyes that do not see are a heart that does not feel"),
	array("who" => "Atherton Bartelby", "quote" => "Eat My Fear"),
	array("who" => "Wiley", "quote" => "Nichi nichi kore kōnichi (Every day is a good day)"),
	array("who" => "marty", "quote" => "It is what it is"),
	array("who" => "marty", "quote" => "wherever you go, there you are"),
	array("who" => "Andrew Cafourek ", "quote" => "You arent thinking big enough"),
	array("who" => "Andrew Cafourek ", "quote" => "Get outside the box"),
	array("who" => "Andrew Cafourek", "quote" => "Do what you can with what you have."),
	array("who" => "Mark Busse", "quote" => "knowledge is power"),
	array("who" => "duffy", "quote" => "by god I wish I had arms."),
	array("who" => "d", "quote" => "Be the river."),
	array("who" => "Noel Jackson", "quote" => "Do what's right for everyone, not just yourself."),
	array("who" => "Mars", "quote" => "Surrender"),
	array("who" => "Yatima", "quote" => "Love, valor, compassion!"),
	array("who" => "Dawson", "quote" => "Just fuckin' do it."),
	array("who" => "Josh Mock", "quote" => "Take a risk."),
	array("who" => "judith", "quote" => "YOU are the beloved guest"),
	array("who" => "Matt Todd", "quote" => "Enjoy yourself."),
	array("who" => "meagneato ", "quote" => "Who do I want to be?"),
	array("who" => "meagneato", "quote" => "What would love do?"),
	array("who" => "quirk", "quote" => "An artist's only concern is to shoot for some kind of perfection, and on his own terms, not anyone else's."),
	array("who" => "quirk", "quote" => "The universe is just a little thing we whipped up for our entertainment the other night, and then all agreed to forget the gag."),
	array("who" => "skampy", "quote" => "we crawl inside of ourselves for control."),
	array("who" => "Terry M", "quote" => "Today you are you, that is truer than true. There is no one alive that is you-er than you."),
	array("who" => "Jack Danger Canty", "quote" => "Someday I will die. What would I like to do before then?"),
	array("who" => "Rafi", "quote" => "Just Live"),
	array("who" => "Rafi", "quote" => "Wake Up to Feel Gooood."),
	array("who" => "Rafi", "quote" => "Pause, Consider, then commit."),
	array("who" => "Rafi", "quote" => "Be Present."),
	array("who" => "Kevin", "quote" => "Live hard"),
	array("who" => "Kevin", "quote" => "Do it"),
	array("who" => "mike mcgrath", "quote" => "You have the wisdom of the ages at your fingertips"),
	array("who" => "Andrew", "quote" => "Meow Meow Meow"),
	array("who" => "Laura", "quote" => "You can do this."),
	array("who" => "kristina", "quote" => "it does not do to dwell on dreams and forget to live."),
	array("who" => "kristina", "quote" => "numbing the pain for a while makes it worse when you finally feel it."),
	array("who" => "Anne", "quote" => "Be Present"),
	array("who" => "Melanie", "quote" => "isn't it wonderful that we all get to grow old together?"),
	array("who" => "Mike", "quote" => "Time flies like the wind, and fruit flies like bananas."),
	array("who" => "Megan64", "quote" => "it is what it is."),
	array("who" => "Foster", "quote" => "I control my life"),
	array("who" => "Peter", "quote" => "Fire and motion."),
	array("who" => "Nicole", "quote" => "Stand like a mountain, bend like the grass."),
	array("who" => "Danny", "quote" => "You are enough."),
	array("who" => "Trimpot", "quote" => "Get in the hole!..."),
	array("who" => "Tom Bridge", "quote" => "Hurry up and lose your first 50 games."),
	array("who" => "Tom Bridge", "quote" => "Own What's Yours."),
	array("who" => "lexi", "quote" => "choice"),
	array("who" => "pj", "quote" => "You're a cartoonist - so CARTOON!"),
	array("who" => "Scott", "quote" => "WTF?"),
	array("who" => "Max", "quote" => "Who are you now, who is the person you want to be, and what are you doing to get there?"),
	array("who" => "Joelg", "quote" => "Keep going."),
	array("who" => "Metal Fatigue", "quote" => "Stop. I'm fine. I'm moving forward."),
	array("who" => "Philip", "quote" => "Remember to put you pants on in the morning before answering the door...."),
	array("who" => "mcwhclan", "quote" => "I'm a tough guy."),
	array("who" => "mcwhclan", "quote" => "I will never be given more than I can handle"),
	array("who" => "madeline", "quote" => "Just keep swimming...just keep swimming..."),
	array("who" => "Sarah", "quote" => "get off your cross already, you look silly up there"),
	array("who" => "Sarah", "quote" => "The world is not out to get you. Sorry, you're just not that important."),
	array("who" => "Sarah", "quote" => "every time I cross the street I feel like Jackie O"),
	array("who" => "Sarah", "quote" => "fake it till you make it, then you're not faking it anymore"),
	array("who" => "Sarah", "quote" => "if it were easy, everyone would be doing it. now try it again."),
	array("who" => "Mike Gray", "quote" => "Live life"),
	array("who" => "Kurt", "quote" => "If he could build a house, then he could mend the hole in the ship"),
	array("who" => "Mark Smith", "quote" => "May something good happen to you today"),
	array("who" => "Liella", "quote" => "Life is, what you think it is"),
	array("who" => "Liella", "quote" => "time-space"),
	array("who" => "Leo", "quote" => "Keep calm and carry on."),
	array("who" => "Yuko", "quote" => "Love, Respect, Believe, Conquer."),
	array("who" => "Yuko", "quote" => "Love what you do, who you are, the people around you."),
	array("who" => "Yuko", "quote" => "Respect your limitations."),
	array("who" => "Yuko", "quote" => "Believe you can complete any goal set before you."),
	array("who" => "Yuko", "quote" => "Conquer any obstacle, fear or doubt and -keep moving forward-."),
	array("who" => "JP", "quote" => "don't waste your time, or time will waste you."),
	array("who" => "megalar", "quote" => "What do I want out of life?"),
	array("who" => "megalar", "quote" => "How does this[current issue] relate to my goal?"),
	array("who" => "pam", "quote" => "Do not try. Do, or do not. There is no try."),
	array("who" => "Eddus", "quote" => "These conditions can never be happened upon again"),
	array("who" => "Eddus", "quote" => "The thing itself"),
	array("who" => "Eddus", "quote" => "It's always worth it"),
	array("who" => "ibookgirl", "quote" => "Life is like one big sigh. Taking it all in, then letting it all go. Breathe deep."),
	array("who" => "Lisa Lu", "quote" => "I will not be defeated this way!"),
	array("who" => "Lisa Lu", "quote" => "You only ever ask your self for input when you are feeling doubt"),
	array("who" => "ethan", "quote" => "WWZD?"),
	array("who" => "Jeano", "quote" => "Live, Love, Laugh"),
	array("who" => "Jeano", "quote" => "the good guy wins."),
	array("who" => "Jeano", "quote" => "The only tyrant I accept in this world is the still voice within."),
	array("who" => "Jeano", "quote" => "Inspiratis Antequam Expiratis (Inhale before you exhale)"),
	array("who" => "Jeano", "quote" => "this moment is good... this moment is good... this is a good one, too... and this one..."),
	array("who" => "Scott", "quote" => "Focusing on the negative only gives it power"),
	array("who" => "casey", "quote" => "Quo Vadimus (Where are we going?)"),
	array("who" => "John", "quote" => "6 billion motherfuckers on the planet and they all wanna be somethin special"),
	array("who" => "Gena", "quote" => "if your life were a movie, what would you be shouting at the screen?"),
	array("who" => "ephelba", "quote" => "Use your powers for good."),
	array("who" => "brendan", "quote" => "Don't worry, just work."),
	array("who" => "brendan", "quote" => "What would Napoleon do..."),
	array("who" => "brendan", "quote" => "I'm a tough nut to crack."),
	array("who" => "Barbara", "quote" => "This is where we are now; we can only move forward."),
	array("who" => "Barbara", "quote" => "Invest in yourself, because nobody else will."),
	array("who" => "Barbara", "quote" => "You can do this."),
	array("who" => "Brandon", "quote" => "Awareness is the key."),
	array("who" => "Mike", "quote" => "We're all screwed anyway, but you still don't want to shit where you sleep"),
	array("who" => "Karen", "quote" => "Be here now"),
	array("who" => "Karen", "quote" => "Serenity now!"),
	array("who" => "Marianne", "quote" => "All Ways Us Living Love."),
	array("who" => "Sassafrass Molly", "quote" => "Relax! Smile, love, be. All is well."),
	array("who" => "Mich", "quote" => "after all, I'm just in the middle"),
	array("who" => "Wardo", "quote" => "What Would The Buddha Do?"),
	array("who" => "rocco", "quote" => "playing things too safe is the most popular way to fail"),
	array("who" => "Cherrie", "quote" => "don't be a dick!!!"),
	array("who" => "kris", "quote" => "motivation comes after action"),
	array("who" => "kris", "quote" => "f*ck it, no one will notice anyway"),
	array("who" => "boo", "quote" => "Saving the World Before Bedtime and Attendance"),
	array("who" => "boo", "quote" => "Students Are not Products"),
	array("who" => "boo", "quote" => "People Are not Disposable"),
	array("who" => "boo", "quote" => "Education Is My Religion"),
	array("who" => "boo", "quote" => "Boredom Is a Deadly Sin"),
	array("who" => "boo", "quote" => "It's All in the Approach"),
	array("who" => "boo", "quote" => "They're small. Take two."),
	array("who" => "boo", "quote" => "Like ta hear it? Here it go."),
	array("who" => "boo", "quote" => "Forgive Me Now You Have No Idea How Much Time It Will Save"),
	array("who" => "Amelie", "quote" => "You are a star."),
	array("who" => "Megiavelli", "quote" => "Every thing's going to be all right."),
	array("who" => "chase", "quote" => "he's got too many irons in the fire."),
	array("who" => "Lhyzz", "quote" => "I can do this"),
	array("who" => "Lhyzz", "quote" => "It will be okay"),
	array("who" => "cronopio", "quote" => "Always try to understand things"),
	array("who" => "Parrot Eyes", "quote" => "I'm on a roll now, or is it a slide?"),
	array("who" => "Parrot Eyes", "quote" => "Rejoice"),
	array("who" => "Lauren", "quote" => "what about malaise, anger, frustration, sadness... not going to make anything with those?"),
	array("who" => "Lauren", "quote" => "And my God, we have to keep on making things."),
	array("who" => "Lauren", "quote" => "Nothing is impossible, if you want it bad enough."),
	array("who" => "deeleea", "quote" => "No Regrets: No Excuses."),
	array("who" => "Ben", "quote" => "Fuck yeah!"),
	array("who" => "Ben", "quote" => "This too will pass"),
	array("who" => "jm", "quote" => "Shut up."),
	array("who" => "SDGrimshaw", "quote" => "keep moving"),
	array("who" => "rambly", "quote" => "it is a perfect moment"),
	array("who" => "henderpa", "quote" => "Leave things better"),
	array("who" => "henderpa", "quote" => "Involve yourself"),
	array("who" => "henderpa", "quote" => "Choose the best"),
	array("who" => "Thomas", "quote" => "Perform random kindness and senseless acts of beauty."),
	array("who" => "Annie", "quote" => "With courage greater than your fear, leap into the unknown and you will fly!"),
	array("who" => "TimTheFoolMan", "quote" => "Don't do anything stupid."),
	array("who" => "Holli", "quote" => "Get over yourself."),
	array("who" => "Diana B.", "quote" => "Life is easy."),
	array("who" => "brian bridges", "quote" => "put the seat down."),
	array("who" => "autonymph", "quote" => "Breathe."),
	array("who" => "Clan", "quote" => "The greater the seeming disadvantage, the greater the possible advantage."),
	array("who" => "jeano", "quote" => "Descretion is the better part of valor"),
	array("who" => "aynne", "quote" => "Accept what is"),
	array("who" => "aynne", "quote" => "You can't hide on a one-way street"),
	array("who" => "aynne", "quote" => "Don't stop til you get enough"),
	array("who" => "aynne", "quote" => "I am the eggman, I am the Walrus, Koo Koo Kutchu"),
	array("who" => "aynne", "quote" => "Chi Sei"),
	array("who" => "aynne", "quote" => "What would Samuel L. Jackson do?"),
	array("who" => "jinjo", "quote" => "Yes"),
	array("who" => "Belynda", "quote" => "You have your whole life to do something, and that's not very long."),
	array("who" => "Christopher", "quote" => "Life is a marathon; you should quit smoking."),
	array("who" => "Mike Lambert", "quote" => "Worry about what you can control."),
	array("who" => "Elizabeth", "quote" => "Vet school"),
	array("who" => "Craig", "quote" => "How can I improve my situation."),
	array("who" => "Josh ", "quote" => "Every second you spend doing something you don't care about proves you don't care about yourself."),
	array("who" => "James", "quote" => "How much time do we have? Very little"),
	array("who" => "Ruff Ruff", "quote" => "The world is my oyster."),
	array("who" => "JWo", "quote" => "let's rock this bitch!"),
	array("who" => "Cathy Von Elm", "quote" => "Buck up, old girl."),
	array("who" => "Claire", "quote" => "Be kind, be kind, be kind."),
	array("who" => "Claire", "quote" => "Fuck them. Be kind to yourself."),
	array("who" => "habile b", "quote" => "yes"),
	array("who" => "Jake", "quote" => "Move"),
	array("who" => "Jake", "quote" => "Eyes Up"),
	array("who" => "Parrot Eyes", "quote" => "I'm on a roll now, or is it a slide?"),
	array("who" => "Parrot Eyes", "quote" => "Rejoice."),
	array("who" => "dingo", "quote" => "learning is not linear"),
	array("who" => "dingo", "quote" => "one life to live"),
	array("who" => " dingo", "quote" => "it was worth it"),
	array("who" => "Grace", "quote" => "If you're thinking about making the move, you're not moving."),
	array("who" => "Ashley", "quote" => "Stick your neck out"),
	array("who" => "Ashley", "quote" => "Fake it until you make it"),
	array("who" => "rambly", "quote" => "it is a perfect moment"),
	array("who" => "NR", "quote" => "what would Da say?"),
	array("who" => "Molly", "quote" => "We're not here for a long time, we're here for a good time."),
	array("who" => "Anna Darron", "quote" => "Don't take life too seriously. you'll never get out alive. write that down."),
	array("who" => "tallierae", "quote" => "It's better to regret somethin ya did than somethin ya didn'd do"),
	array("who" => "tallierae", "quote" => "I ain't about to go straight."),
	array("who" => "tallierae", "quote" => "Eyes wide mine, suddenly everything flies by fine"),
	array("who" => "Roberto Leibman", "quote" => "Be Present"),
	array("who" => "Kate", "quote" => "Think Positive"),
	array("who" => "Emlly", "quote" => "Shit'll buff out"),
	array("who" => "ingrid", "quote" => "I have permission to fail."),
	array("who" => "MARY", "quote" => "live like you mean it, spend like you can afford it"),
	array("who" => "MissLady", "quote" => "resist psychic death."),
	array("who" => "dan", "quote" => "write"),
	array("who" => "dan", "quote" => "read"),
	array("who" => "dan", "quote" => "guitar"),
	array("who" => "dan", "quote" => "exercise"),
	array("who" => "dan", "quote" => "save"),
	array("who" => "dan", "quote" => "shut up"),
	array("who" => "dan", "quote" => "stay sober"),
	array("who" => "dan", "quote" => "language"),
	array("who" => "dan", "quote" => "relax"),
	array("who" => "dan", "quote" => "be nice."),
	array("who" => "pirate maki", "quote" => "Perfection is boring."),
	array("who" => "pirate maki", "quote" => "Life's an unsolved mystery. Those who solve it, don't talk about it. Those who don't- talk about it alot."),
	array("who" => "shannon", "quote" => "contradiction = balance"),
	array("who" => "chat'boux", "quote" => "If you're not going to do your best work now, when are you going to do it?"),
	array("who" => "emily", "quote" => "What's stopping you?"),
	array("who" => "Esthrebelle", "quote" => "What you seek also seeks you."),
	array("who" => "Mark", "quote" => "Take Care of Business"),
	array("who" => "Mark", "quote" => "Don't Forget To Be Awesome."),
	array("who" => "Jamie", "quote" => "Friends applaud, the comedy is finished"),
	array("who" => "jp", "quote" => "momentum."),
	array("who" => "initialdescent", "quote" => "Start over."),
	array("who" => "mousewords", "quote" => "When you decide to be something, then be it"),
	array("who" => " ", "quote" => "The world has the habit of making room for the man whose actions show that he knows where he is going."),
	array("who" => "mousewords", "quote" => "Be your own hero"),
	array("who" => "mousewords", "quote" => "What would the hero in you do?"),
	array("who" => "lovedTheShow", "quote" => "it's judgment that defeats us."),
	array("who" => "lovedTheShow", "quote" => "a man not busy getting born is busy getting dead."),
	array("who" => "lovedTheShow", "quote" => "motherfuckers choke under pressure."),
	array("who" => "MiMi", "quote" => "People often say that motivation doesn't last. Well, neither does bathing -- that's why we recommend it daily."),
	array("who" => "Phil South", "quote" => "what's the BEST that could happen?"),
	array("who" => "Phil South", "quote" => "have you MADE something today?"),
	array("who" => "Ben", "quote" => "they're not your ducks"),
	array("who" => "Jonathan", "quote" => "Be Here Now."),
	array("who" => "Jonathan", "quote" => "I am alive, I am at home."),
	array("who" => "Jonathan", "quote" => "You should just do whatever you want to do."),
	array("who" => "Jonathan", "quote" => "Go for a walk. Even if you end up in prison you can still go for a walk."),
	array("who" => "Jonathan", "quote" => "Fuck it dude. Let's go bowling."),
	array("who" => "sally", "quote" => "use your stress to relax"),
	array("who" => "anu", "quote" => "always choose again."),
	array("who" => "Peter", "quote" => "Get diligent."),
	array("who" => "Sport", "quote" => "If it didn't hurt, it wouldn't be working."),
	array("who" => "Carl", "quote" => "KEEP YOUR EARS UP"),
	array("who" => "Wren", "quote" => "Cooking"),
	array("who" => "Wren", "quote" => "Cleaning"),
	array("who" => "Wren", "quote" => "Cheering up."),
	array("who" => "Wren", "quote" => "What would emma do?"),
	array("who" => "Wren", "quote" => "Imperfect but intrinsically good."),
	array("who" => "Jill", "quote" => "keep moving forward. One thing will follow the next."),
	array("who" => "remis velisque", "quote" => "If the wind will not serve, take to the oars."),
	array("who" => "remis velisque", "quote" => "Remis velisque (with oars and sails)"),
	array("who" => "remis velisque", "quote" => "Grab the f**king oars and start rowing."),
	array("who" => "SkyWriter", "quote" => "I am strong, and my path is clear"),
	array("who" => "SkyWriter", "quote" => "The little things never bothered me much"),
	array("who" => "SkyWriter", "quote" => "Never thought I'd be doing THIS for a living!"),
	array("who" => "Eleonore", "quote" => "Just do it."),
	array("who" => "Eleonore", "quote" => "Every decision you make creates your future."),
	array("who" => "heidrun", "quote" => "do one thing every day that scares you"),
	array("who" => "tash", "quote" => "Dreams are meant to come true. Why else would nature incite us to have them?"),
	array("who" => "stephan", "quote" => "This too shall pass."),
	array("who" => "stephan", "quote" => "Dissertation"),
	array("who" => "coliwilso", "quote" => "If you're going through hell, keep going!"),
	array("who" => "mike________*__", "quote" => "It's up to you."),
	array("who" => "Caitlin", "quote" => "Because every little thing is gonna be alright..."),
	array("who" => "Delvy", "quote" => "just f_ it"),
	array("who" => "Delvy", "quote" => "these are all people. Everyone is a person."),
	array("who" => "charliebluefish", "quote" => "Charlie is beautiful."),
	array("who" => "charliebluefish", "quote" => "This is not vanity; it's self-acceptance."),
	array("who" => "Christian Gindlesperger", "quote" => "Always wipe, stay off the pipe, and if anyone gets in your face, just tell 'em, 'I'm chillin''."),
	array("who" => "Christian Gindlesperger", "quote" => "Keep true to the dreams of thy youth."),
	array("who" => "Stacy Lenore", "quote" => "Just Do It."),
	array("who" => "natisha", "quote" => "every day is just one day"),
	array("who" => "natisha", "quote" => "take my hand, 'cause we're walking out of here."),
	array("who" => "natisha", "quote" => "sometimes, all I need is the air that I breathe"),
	array("who" => "natisha", "quote" => "Things are as normal as you make them"),
	array("who" => "Craig", "quote" => "After the bad weather comes the fine weather."),
	array("who" => "jessica", "quote" => "Stop looking at blogs."),
	array("who" => "jessica", "quote" => "I do the best I can, and I'm satisfied with that. Sigh."),
	array("who" => "Y2", "quote" => "YOU DON'T HAVE MUCH TIME LEFT"),
	array("who" => "272", "quote" => "It's a choice"),
	array("who" => "stephstereo", "quote" => "Its not what you want of life, its what life wants of you."),
	array("who" => "stephstereo", "quote" => "In any hour you can choose to liberate the future."),
	array("who" => "b.hotep", "quote" => "go join another person's expression of self & do nothing toward your own actualization."),
	array("who" => "Kate", "quote" => "Don't panic."),
	array("who" => "Erin", "quote" => "Do what you can do. Don't sweat the rest."),
	array("who" => "molo", "quote" => "It's okay it's okay it's okay it's okay it's o-KAY."),
	array("who" => "Colin", "quote" => "Love everyone, Serve everyone, Remember God."),
	array("who" => "dave", "quote" => "you can't heal what you can't feel"),
	array("who" => "jenks", "quote" => "greet with love."),
	array("who" => "Tony L Joy", "quote" => "lengthen your line"),
	array("who" => "Tony L Joy", "quote" => "Stand tall, or not at all."),
	array("who" => "Elle", "quote" => "Do your best!"),
	array("who" => "N. Francesca", "quote" => "I'm diggin' your core."),
	array("who" => "Wendy ROBY", "quote" => "Get The Fuck On With It Wendy"),
	array("who" => "Wendy ROBY", "quote" => "THEY'RE ALL WANKERS."),
	array("who" => "Marthe", "quote" => "Life is a gift, that's why we call it the present."),
	array("who" => "jackie", "quote" => "Lack of planning on your part doesn't constitute an emergency on mine."),
	array("who" => "chloe", "quote" => "If you're not going to do your best work right now, when are you going to do it?"),
	array("who" => "Tom", "quote" => "All my possessions for a moment of time."),
	array("who" => "Kristen", "quote" => "Just because I can, doesn't mean I should"),
	array("who" => "Kristen", "quote" => "Because I can, I should"),
	array("who" => "Kristen", "quote" => "Nobody cares"),
	array("who" => "Sara", "quote" => "I'm not going to want to do this later any more than I want to do it now, so I might as well do it now and get it over with."),
	array("who" => "Sara", "quote" => "Think ahead"),
	array("who" => "Sara", "quote" => "Regret is a waste of time."),
	array("who" => "Sara", "quote" => "Hate is a waste of time."),
	array("who" => "Sara", "quote" => "Do not hate player. Hate game."),
	array("who" => "Sara", "quote" => "So, what's your excuse?"),
	array("who" => "tech_sam", "quote" => "Who says?"),
	array("who" => "tech_sam", "quote" => "fight!"),
	array("who" => "Lexy", "quote" => "What happens, happens"),
	array("who" => "Lexy", "quote" => "Less thinking, more doing")
);

?>
